version: "3"
services:
    node-app:
        ports: 
            - "${EXPRESS_PORT}:${EXPRESS_PORT}"
        depends_on:
            - mongo

    mongo:
        image: mongo

    redis:
        image: redis