version: "3"
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - app-node-modules:/app/node_modules
        environment: 
            - NODE_ENV=development
            - EXPRESS_PORT=3000
            - MONGO_IP=mongo
            - MONGO_PORT=27017
            - MONGO_USER=dev
            - MONGO_PASSWORD=dev
            - REDIS_SESSION_SECRET=dev
        ports:
            - 3000:3000
            - 9229:9229
        command: npm run dev

    mongo:
        volumes:
            - mongo-db-dev:/data/db
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=dev
            - MONGO_INITDB_ROOT_PASSWORD=dev

volumes:
    mongo-db-dev:
    app-node-modules: